### ISSUE TITLE
VM Code - WriteIf

### ISSUE THREAD

**Issue by thomaschiari** [Maraba23/bits-e-proc-Dromedario#93]

**Comment by thomaschiari** [comment]
![goto_if](https://user-images.githubusercontent.com/73441789/202938938-b7fe95cd-f90e-45dd-9b4b-304297311241.png)

**Comment by thomaschiari** [comment]
🤨 @P-ASilva

**Comment by JoaoLucasMBC** [comment]
🤨 @P-ASilva

@rafaelcorsi 
Subir módulo para PR sem estar passando no teste é coisa de troglodita ou não?

**Comment by rafaelcorsi** [comment]
na main é
